### ISSUE TITLE
When I try to load the script it just gets loading.

### ISSUE THREAD

**Issue by TheUnaverage** [superyu1337/RageSU#25]
**Describe the bug**
When I try to use the lua a message box appears saying "Loading..." and after multiple minutes nothing ever happens

**To Reproduce**
1. Load Lua and it just says "Loading..."

**Comment by yahyapasatrr** [comment]
same problem

**Comment by SupSupSupxD** [comment]
Sameee

**Comment by Yelex1206** [comment]
yeah this happens to me too :(

**Comment by Colabottle442** [comment]
yeep, same.

**Comment by pNoName1337** [comment]
same problem, @superyor pls fix it

**Comment by ticzz** [comment]
https://discordapp.com/channels/437995927559471105/568137818350682122/738501562866991164

READ THIS GUYS!!!!!

**Comment by Hunter-J** [comment]
> https://discordapp.com/channels/437995927559471105/568137818350682122/738501562866991164
> 
> READ THIS GUYS!!!!!

That link doesn't work :/

**Comment by Qukallon-1** [comment]
same.

**Comment by ticzz** [comment]
for me link still works.. u joined the channel or no?
https://discord.com/channels/437995927559471105/568137818350682122/738501562866991164

also the lua works but anyways it needs to get updated because it doesnt work like supposed after aimware antiaim updates
